version: '3.8'
services:
  web:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
  db:
    image: 'mongo:latest'
    container_name: db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - .dbdata-volume:/data/db

volumes:
  dbdata-volume: