version: '3.8'
services:
  web:
    build: .
    command: yarn dev
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
    networks:
      - app-network
  db:
    image: 'mongo:latest'
    container_name: db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - .dbdata-volume:/data/db
    networks:
      - app-network

volumes:
  dbdata-volume:

networks:
  app-network:
    driver: bridge