version: '3.8'
services:
  web:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app
    ports:
      - "3333:3333"
  db:
    image: 'mongo'
    container_name: db
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=nodeuser
      - MONGO_INITDB_ROOT_PASSWORD=nodeuser
      - MONGO_INITDB_DATABASE=db
      
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db